/*** GENERATED BY @bugsounet Gateway v3.6.2 ***/
/*** https://forum.bugsounet.fr **/

var config = {
  address: 'localhost',
  electronOptions: {
    webPreferences: {
      webviewTag: true
    }
  },
  port: 8080,
  basePath: '/',
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1'
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  language: 'de',
  locale: 'de-CH',
  logLevel: [
    'INFO',
    'LOG',
    'WARN',
    'ERROR'
  ],
  timeFormat: 24,
  units: 'metric',
  modules: [
    {
      module: 'alert'
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {
        sendUpdatesNotifications: true
      }
    },
    {
      module: 'clock',
      position: 'top_left'
    },
    {
      module: 'calendar',
      header: 'Feiertage',
      position: 'top_left',
      config: {
        calendars: [
          {
            fetchInterval: 604800000,
            symbol: 'calendar-check',
            url: 'https://onlinekalender.info/feiertage/schweiz.ics'
          }
        ]
      }
    },
    {
      module: 'MMM-GoogleAssistant',
      configDeepMerge: true,
      config: {
        debug: false,
        responseConfig: {
          useFullscreen: false,
          responseOutputCSS: 'response_output.css',
          screenOutputTimer: 5000,
          useChime: true,
          confirmationChime: true
        },
        assistantConfig: {
          lang: 'de-DE',
          latitude: 47.20791,
          longitude: 7.53714,
          deviceRegistred: false
        },
        recipes: [
          '../../EXT-Pages/recipe/EXT-Pages.js',
          '../../EXT-Spotify/recipe/EXT-Spotify.js'
        ]
      }
    },
    {
      module: 'Gateway',
      config: {
        debug: false,
        username: 'akgo',
        password: 'akgo',
        CLIENT_ID: '281888629752-hbb53sq2teolbrimq945ns9sflcni3nb.apps.googleusercontent.com'
      }
    },
    {
      module: 'EXT-Alert',
      config: {
        debug: false,
        ignore: []
      }
    },
    {
      module: 'EXT-Updates',
      configDeepMerge: true
    },
    {
      module: 'EXT-Detector',
      position: 'top_left',
      disabled: false,
      configDeepMerge: true,
      config: {
        debug: false,
        useIcon: false,
        touchOnly: false,
        detectors: [
          {
            detector: 'Snowboy',
            Model: 'smart_mirror',
            Sensitivity: null
          },
                    {
            detector: 'Snowboy',
            Model: 'jarvis',
            Sensitivity: null
          }
        ]
      }
    },
    {
      module: 'EXT-Welcome',
      config: {
        welcome: 'Sali, schon lange nicht mehr gesehen!'
      }
    },
    {
      module: 'compliments',
      position: 'lower_third',
      config: {
        complimets: {
     			anytime: ["Sali!"],
			    morning: ["Guten Morgen!", "Geniesse Deinen Tag!", "Wie hast du geschlafen?", "Moin Moin!"],
			    afternoon: ["Wie geht's?", "Du siehst gut aus!"],
			    evening: ["Guten Abend", "Wie war Dein Tag"],
          rain: ["Boah, sieht das Schrecklich aus draussen!"],
          day_sunny: ["Heute ist dein Glückstag!"],
			    "....-01-01": ["Frohes Neues!"],
          "....-10-31": ["Happy Halloween!"],
          "....-06-15": ["Viel Glück zum Geburtstag, Akin!"],
        }
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: 'Wetterprognose aktuell',
      config: {
        weatherProvider: 'openweathermap',
        type: 'current',
        windUnits: "metric",
        showHumidity: true,
        degreeLabel: true,
        showPrecipitationProbability: true,
        location: 'Kanton Solothurn',
        locationID: '2658563',
        apiKey: 'ea259a79b4dda357a406e68eaa75d1f4'
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: 'Wetterprognose',
      config: {
        weatherProvider: 'openweathermap',
        type: 'forecast',
        degreeLabel: true,
        initialLoadDelay: 1000,
        location: 'Kanton Solothurn',
        locationID: '2658563',
        apiKey: 'ea259a79b4dda357a406e68eaa75d1f4'
      }
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      animateIn: "slideInLeft",
      animateOut: "slideOutRight",
      config: {
        feeds: [
          {
            title: 'SRF News',
            url: 'https://www.srf.ch/news/bnf/rss/1890'
          },
          {
            title: "SRF Sport News",
            url: "https://www.srf.ch/sport/bnf/rss/718"
          },
          {
            title: 'SRF Kultur News',
            url: 'https://www.srf.ch/kultur/bnf/rss/454'
          },
          {
            title: 'SRF Wissen News',
            url: 'https://www.srf.ch/bnf/rss/630'
          },
        ],
        showSourceTitle: true,
        showPublishDate: true,
        broadcastNewsFeeds: true,
        broadcastNewsUpdates: true,
        ignoreOlderThan: 7*86400000,
        updateInterval: 20000
      }
    },
    {
      module: 'EXT-Screen',
      position: 'bottom_left',
      animateIn: 'flipInX',
      animateOut: 'flipOutX',
      disabled: false,
      config: {
        debug: false,
        animateBody: true,
        autoDimmer: true,
        delay: 120000,
        mode: 1,
        displayCounter: true,
        displayBar: true,
        displayStyle: 'Text',
        displayLastPresence: true,
        lastPresenceTimeFormat: 'LL H:mm',
        detectorSleeping: false,
        gpio: 20,
        clearGpioValue: true,
        sound: true,
        touchMode: 0,
        ON: [
        {
          dayOfWeek: [1,2,3,4,5,6],
          hour: 06,
          minute: 15,
        },
        {
          dayOfWeek: [0],
          hour: 08,
          minute: 15,
        }
      ],
        OFF: [
         {
          dayOfWeek: [0,1,2,3,4,5,6],
          hour: 22,
          minute: 30,
        }
      ]
      }
    },
    {
      module: 'EXT-Pages',
      position: 'bottom_bar',
      disabled: false,
      config: {
        pages: {
          '0': [
            'compliments'
          ],
          '1': [
            'clock',
            'calendar',
            'weather',
            'newsfeed'
          ],
          '2': [
            'EXT-YouTubeCast',
            'EXT-Volume'
          ]
        },
        fixed: [
          'updatenotification',
          'EXT-Spotify',
          'EXT-Welcome',
          'EXT-Update',
          'EXT-Alert',
          'EXT-Screen'
        ],
        hiddenPages: {
          "normal": [ "clock", "compliments", "calendar", "weather", "newsfeed" ],
          "youtube": [ "EXT-YoutubeCast" ]
          
        },
        animationTime: 1000,
        rotationTime: 0,
        rotationTimes: {},
        homePage: 0,
        indicator: true,
        hideBeforeRotation: false,
        Gateway: {},
        loading: 'loading-screen.gif'
      }
    },
    {
      module: 'EXT-Spotify',
      position: 'bottom_left',
      animateIn: 'flipInX',
      animateOut: 'flipOutX',
      disabled: false,
      config: {
        updateInterval: 1000,
        idleInterval: 10000,
        useBottomBar: false,
        CLIENT_ID: '06a5ecfbeb8641c29655f59b92a61e9d',
        CLIENT_SECRET: 'd46868383250494087b4a8dc96975b6a'
      }
    },
    {
      module: 'EXT-Librespot',
      disabled: false,
      config: {
        debug: false,
        email: 'akin.godglueck@outlook.de',
        password: 'JamaicaA',
        deviceName: 'MagicMirror',
        minVolume: 50,
        maxVolume: 100
      }
    },
    {
      module: 'EXT-Volume',
      disabled: false,
      config: {
        debug: false,
        startSpeakerVolume: 100,
        startRecorderVolume: 50,
        syncVolume: true
      }
    },
    {
      module: 'EXT-YouTubeCast',
      position: 'bottom_center',
      disabled: false,
      config: {
        debug: false,
        fullscreen: false,
        width: '1000px',
        height: '1000px',
        alwaysDisplayed: true,
        castName: 'MagicMirror',
        port: 8569
      }
    }
  ]
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
